const assert=require('node:assert/strict');
const load=require('./load-ts.cjs');
const r=load('lib/setter-rules.ts');
const session={id:'s1',date:'2026/9/7',period:'1',grade1Subject:'국어',grade2Subject:'수학',grade3Subject:'시험 없음',rooms:'1-1,2-1'};
const base={id:'a',name:'A',subject:'국어',homeroom:'',role:'교과교사',max:9,unavailable:''};
const standby={...base,setterGrade:1,setterSubject:'국어',setterDuty:'standby'};
const assistant={...base,id:'b',setterGrade:1,setterSubject:'국어',setterDuty:'assistant'};
assert.deepEqual(r.examSubjects(session),['국어','수학']);
assert.deepEqual(r.officeStandbyTeachers(session,[standby,assistant]).map(t=>t.id),['a']);
assert.equal(r.setterAssistantForSession(assistant,session),true);
assert.equal(r.setterAssistantAllowedRoom(assistant,session,'2-1'),true);
assert.equal(r.setterAssistantAllowedRoom(assistant,session,'1-1'),false);
assert.equal(r.singleGradeSetterException(assistant,{...session,grade2Subject:'시험 없음'},'assistant'),true);
assert.equal(r.singleGradeSetterException(assistant,{...session,grade2Subject:'시험 없음'},'chief'),false);
const sameSubject={...session,grade1Subject:'수학',grade2Subject:'수학'};
const grade1Standby={...standby,setterSubject:'수학'};
const grade2Standby={...standby,id:'c',setterGrade:2,setterSubject:'수학'};
assert.deepEqual(r.officeStandbyTeachers(sameSubject,[grade1Standby,grade2Standby]).map(t=>t.id),['a','c']);
assert.equal(r.setterAssistantAllowedRoom({...assistant,setterSubject:'수학'},sameSubject,'2-1'),true);
assert.equal(r.setterAssistantAllowedRoom({...assistant,setterSubject:'수학'},sameSubject,'1-1'),false);
assert.deepEqual(r.officeStandbyTeachers(sameSubject,[{...grade1Standby,setterGrade:undefined}]),[]);
console.log('PASS: setter subjects, office standby, other-grade assistant and single-grade exception');
