const assert = require('node:assert/strict');
const fs = require('node:fs');
const ts = require('typescript');
const Module = require('node:module');
const ExcelJS = require('exceljs');
const m = new Module(require('node:path').resolve('lib/teacher-roster.ts'), module);
m.filename = require('node:path').resolve('lib/teacher-roster.ts');
m.paths = module.paths;
m._compile(ts.transpile(fs.readFileSync('lib/teacher-roster.ts', 'utf8'), { module: ts.ModuleKind.CommonJS, target: ts.ScriptTarget.ES2022, esModuleInterop: true }), m.filename);
const { parseRoster, applyRoster, createRosterTemplate, readRoster } = m.exports;
(async () => {
  const bytes = await createRosterTemplate();
  const wb = new ExcelJS.Workbook();
  await wb.xlsx.load(bytes);
  const sheet = wb.getWorksheet('교사명단');
  assert.equal(sheet.getCell('C2').numFmt, '@');
  assert.equal(sheet.getCell('B2').dataValidation.type, 'list');
  assert.ok(wb.definedNames.getRanges('TeacherRooms').ranges.length);
  assert.equal(parseRoster(wb).rows.length, 0);
  sheet.getRow(2).values = ['김가람', '국어', '1-10', '교과교사', 0];
  sheet.getRow(3).values = ['이누리', '없음', '', '비교과', 2];
  let preview = parseRoster(wb);
  assert.deepEqual(preview.errors, []);
  assert.equal(preview.rows.length, 2);
  assert.equal(preview.rows[0].max, 0);
  assert.equal(preview.rows[1].subject, '');
  const current = [{ id: 'old', name: '김가람', subject: '수학', homeroom: '', role: '교과교사', max: 4, unavailable: 's1' }, { id: 'keep', name: '박다온', unavailable: '' }];
  const merged = applyRoster(current, preview.rows, 'merge', () => 'new');
  assert.equal(merged.length, 3);
  assert.equal(merged.find(t => t.id === 'old').unavailable, 's1');
  assert.equal(merged.find(t => t.id === 'old').subject, '국어');
  assert.equal(applyRoster(current, preview.rows, 'replace', () => 'new').length, 2);
  assert.throws(() => applyRoster([...current, { ...current[0], id: 'duplicate' }], preview.rows, 'merge', () => 'new'), /동명이인/);
  sheet.getRow(4).values = ['김가람', '알수없음', '4-1', '교사', -1];
  preview = parseRoster(wb);
  assert.match(preview.errors.join(), /4행/);
  assert.match(preview.errors.join(), /이름 중복/);
  sheet.getRow(4).values = ['홍길동', '영어', '없음', '강사', { formula: '1+1', result: 2 }];
  assert.match(parseRoster(wb).errors.join(), /수식/);
  sheet.getRow(4).values = [];
  const buffer = await wb.xlsx.writeBuffer();
  const loaded = await readRoster({ name: '명단.xlsx', size: buffer.length, arrayBuffer: async () => buffer });
  assert.equal(loaded.rows.length, 2);
  await assert.rejects(() => readRoster({ name: 'file.xls', size: 1 }), /xlsx/);
  await assert.rejects(() => readRoster({ name: 'file.xlsx', size: 6 * 1024 * 1024 }), /5MB/);
  const empty = new ExcelJS.Workbook(); empty.addWorksheet('Sheet1').addRow(['이름']);
  assert.throws(() => parseRoster(empty), /열이 필요/);
  console.log('PASS: template roundtrip, five fields, invalid values, duplicate names, formula rejection, merge/replace preservation, file limits');
})().catch(error => { console.error(error); process.exitCode = 1; });
